spring:
  datasource:
    url: jdbc:mysql://localhost:3306/violationdb?serverTimezone=UTC&characterEncoding=utf8&useSSL=true
#    url: jdbc:mysql://119.23.75.183:3306/violationdb?serverTimezone=UTC&characterEncoding=utf8&useSSL=true
    username: "root"
    password: "000000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
# THYMELEAF
  thymeleaf:
    servlet:
      content-type: text/html
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  webflux:
    static-path-pattern: /public/**
#MYBATIS
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.code.vv.mapper
# DEBUG
debug: true
#PAGRHELPER
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql